### ISSUE TITLE
Buffering lineStrings and polygons

### ISSUE THREAD

**Issue by liebrand** [mapbox/cheap-ruler#17]
Hi there,

Any plans to update this extremely useful ruler to also be able to buffer line strings and polygons? Or would the calculations required mean that it ultimately would be just as fast as turf (and thus you'd be better off using turf to start with)?

/Cheers,
Jelte

**Comment by mourner** [comment]
No, buffering is unfortunately out of scope for this library because it's an extremely challenging algorithmic problem.
