### ISSUE TITLE
along giving incorrect results

### ISSUE THREAD

**Issue by LR-brendan** [mapbox/cheap-ruler#46]
I've implemented `along` into a project and noticed some strange results (returned points being either too far along the line, or not far enough).
I just found this [Codepen ](https://codepen.io/re5pawn/pen/NAobxv?editors=0011) via Google and it is seems to be giving incorrect results too.
The green circle should be 250m from the top blue circle, but measuring the distance on Google Maps puts it not even close, at ~208m
![image](https://user-images.githubusercontent.com/45767170/98977904-114f1800-2511-11eb-9267-f22feb9a28e2.png)

![image](https://user-images.githubusercontent.com/45767170/98977292-5de62380-2510-11eb-8f6d-28c5bcc71d04.png)

Interestingly, `ruler.distance` puts the total line length at 852m, but Google Maps says it's 739m.

Am I missing something here?

PS. the codepen example is using an older version, but changing to v3.0.1, and after a few tweaks to get it running, the results are basically the same.

**Comment by mourner** [comment]
The issue is that Leaflet accepts coordinates in `[latitude, longitude]` form, while Cheap Ruler assumes `[longitude, latitude]`. If you swap the order, the calculation is correct.

**Comment by LR-brendan** [comment]
Well that's embarrassing! Thanks!
