### ISSUE TITLE
Inside "point+distance" version

### ISSUE THREAD

**Issue by sw360cab** [mapbox/cheap-ruler#47]
Similar to:

`insideBBox`

is there an utility to achieve

`inside *circle* given point+distance`

**Comment by sw360cab** [comment]
Correct me if I am wrong.

This can be achieved via `distance` method

```javascript
/*
const inside = ruler.insideCircleArea([30.5, 50.5], [30, 50], 5000); // in meters
     * //=inside
 */
insideCircleArea(p, refPoint, refDistance) {
  return this.distance(p,refPoint) <= refDistance;
}
```

Provided that *refDistance* should be using same unit of `CheapRuler`, otherwise further conversions may be needed.

**Comment by mourner** [comment]
I don't think this needs another method — `ruler.distance(a, b) <= radius` is simple enough.
