### ISSUE TITLE
Please, consider to specify a license

### ISSUE THREAD

**Issue by ifraixedes** [mapbox/cheap-ruler#5]
Please, consider to specify a license

First of all, thanks to release this work on a public repository.

Nonetheless, this repo doesn't have any concrete license (or it isn't easy to see), so I would like that you consider to choose one to avoid the confusion that it causes with its absence, the work has applied the default copyright laws which the most of the people we aren't sure the implications because we aren't lawyers.

[This page may help you to decide which one is more convenient for you and all the benefits that an open license has over a closed one](https://help.github.com/articles/open-source-licensing/), however, don't get me wrong, choose the one that fits better to your specific case, independently if it's open or not.

Thanks for considering.

**Comment by mourner** [comment]
The license was specified in [package.json](https://github.com/mapbox/cheap-ruler/blob/master/package.json#L30), but I'll add it as text in the repo now too.

**Comment by ifraixedes** [comment]
I saw it, but now it's easy to know about it.

Thanks
