### ISSUE TITLE
A missed API definition (pointToSegmentDistance) published on https://www.npmjs.com/

### ISSUE THREAD

**Issue by geonoon** [mapbox/cheap-ruler#50]
Currently the latest version  (3.0.1) of the cheap-ruler library code at https://github.com/mapbox/cheap-ruler  and  at https://www.npmjs.com/package/cheap-ruler are a little bit different. There is an error at the latter.

As to the file cheap-ruler.d.ts, the API pointToSegmentDistance() is missed at https://www.npmjs.com/package/cheap-ruler.

Please fix this error as soon as possible.

**Comment by mourner** [comment]
Published as 3.0.2.
